[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/**",
  "http://192.168.1.192:3000/**"
]

[auth.email]
enable_signup = true
enable_confirmations = true

[inbucket]
enabled = true
[functions.member_uuid_cleanup]
enabled = true
verify_jwt = true
import_map = "./functions/member_uuid_cleanup/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/member_uuid_cleanup/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/member_uuid_cleanup/*.html" ]

[functions.book_rank]
enabled = true
verify_jwt = true
import_map = "./functions/book_rank/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/book_rank/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/book_rank/*.html" ]
