

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."books" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "author" "text" NOT NULL,
    "genre" "text" NOT NULL
);


ALTER TABLE "public"."books" OWNER TO "postgres";


ALTER TABLE "public"."books" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Book_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."books_additional_information" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "book_id" bigint NOT NULL
);


ALTER TABLE "public"."books_additional_information" OWNER TO "postgres";


ALTER TABLE "public"."books_additional_information" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Books_additional_information_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."chapters" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "xhtml" "text" NOT NULL,
    "seq" bigint NOT NULL,
    "title" "text" NOT NULL,
    "book_id" bigint NOT NULL
);


ALTER TABLE "public"."chapters" OWNER TO "postgres";


ALTER TABLE "public"."chapters" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Chapters_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."mainvisual" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "sub_title" "text",
    "book_id" bigint NOT NULL,
    "book_link" "text",
    "slide_order" bigint,
    "img_path" "text" NOT NULL,
    "agree" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."mainvisual" OWNER TO "postgres";


ALTER TABLE "public"."mainvisual" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Mainvisual_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."member" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text" NOT NULL,
    "user_id" "text" NOT NULL,
    "user_level" "text" NOT NULL
);


ALTER TABLE "public"."member" OWNER TO "postgres";


COMMENT ON TABLE "public"."member" IS 'member';



COMMENT ON COLUMN "public"."member"."email" IS 'email';



COMMENT ON COLUMN "public"."member"."user_id" IS 'user_id';



ALTER TABLE "public"."member" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."member_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."books"
    ADD CONSTRAINT "Book_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."books_additional_information"
    ADD CONSTRAINT "Books_additional_information_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."chapters"
    ADD CONSTRAINT "Chapters_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."mainvisual"
    ADD CONSTRAINT "Mainvisual_order_key" UNIQUE ("slide_order");



ALTER TABLE ONLY "public"."mainvisual"
    ADD CONSTRAINT "Mainvisual_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."member"
    ADD CONSTRAINT "member_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."member"
    ADD CONSTRAINT "member_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."member"
    ADD CONSTRAINT "member_user_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."books_additional_information"
    ADD CONSTRAINT "Books_additional_information_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."chapters"
    ADD CONSTRAINT "Chapters_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."mainvisual"
    ADD CONSTRAINT "Mainvisual_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE CASCADE;



CREATE POLICY "Policy with security definer functions" ON "public"."books" USING (true);



CREATE POLICY "Policy with security definer functions" ON "public"."chapters" USING (true);



CREATE POLICY "Policy with security definer functions" ON "public"."mainvisual" USING (true);



CREATE POLICY "Policy with security definer functions" ON "public"."member" USING (true);



ALTER TABLE "public"."books" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."books_additional_information" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."chapters" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."mainvisual" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."member" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";












































































































































































































GRANT ALL ON TABLE "public"."books" TO "anon";
GRANT ALL ON TABLE "public"."books" TO "authenticated";
GRANT ALL ON TABLE "public"."books" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Book_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Book_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Book_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."books_additional_information" TO "anon";
GRANT ALL ON TABLE "public"."books_additional_information" TO "authenticated";
GRANT ALL ON TABLE "public"."books_additional_information" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Books_additional_information_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Books_additional_information_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Books_additional_information_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."chapters" TO "anon";
GRANT ALL ON TABLE "public"."chapters" TO "authenticated";
GRANT ALL ON TABLE "public"."chapters" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Chapters_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Chapters_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Chapters_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."mainvisual" TO "anon";
GRANT ALL ON TABLE "public"."mainvisual" TO "authenticated";
GRANT ALL ON TABLE "public"."mainvisual" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Mainvisual_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Mainvisual_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Mainvisual_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."member" TO "anon";
GRANT ALL ON TABLE "public"."member" TO "authenticated";
GRANT ALL ON TABLE "public"."member" TO "service_role";



GRANT ALL ON SEQUENCE "public"."member_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."member_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."member_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
